version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8800:80
        depends_on:
            - app
        container_name: ${DOCKER_APP_NAME}_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: ${DOCKER_APP_NAME}_app

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DOCKER_DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_ROOT_PASSWORD}
        ports:
            - 8810:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: ${DOCKER_APP_NAME}_db

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_ROOT_PASSWORD}
        ports:
            - 8080:80
        container_name: ${DOCKER_APP_NAME}_phpmyadmin
